"""__name__

Revision ID: 2c83650b4b72
Revises: cb5cc7bcf8aa
Create Date: 2023-07-03 14:38:01.824255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2c83650b4b72'
down_revision = 'cb5cc7bcf8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('modified', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'modified')
    op.drop_column('user', 'created')
    # ### end Alembic commands ###