"""Add cost to message

Revision ID: 6552c088408a
Revises: 00456645b544
Create Date: 2023-08-02 23:11:33.696732

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6552c088408a'
down_revision = '00456645b544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('cost', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'cost')
    # ### end Alembic commands ###
