"""Add hashed_password column to user table

Revision ID: 72585cc7bafd
Revises: 339a22e3f689
Create Date: 2023-06-16 11:21:13.298099

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72585cc7bafd'
down_revision = '339a22e3f689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='default_value'
        ),
    )
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_column('user', 'created')
    op.drop_column('user', 'modified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
